dynamic_nav_node:
  ros__parameters:
    forward_speed: 0.25        # [m/s]
    rotate_speed: 0.8          # [rad/s]
    obstacle_threshold: 0.6    # [m]
    clear_threshold: 1.0       # [m]
    control_period: 0.08       # [s]
